sub_car_topic: /car_detection
pub_car_projected_topic: /car_projected
pub_markers_topic: /car_projected_markers

frame_id: base_link

#해상도 1280*720 일때 내적 파라미터
# camera:
#   fx: 832.4660
#   fy: 844.8521
#   cx: 688.4296
#   cy: 316.8229
#   height: 0.75
#   pitch_deg: -14.5   # 아래로 15도면 -15, 위로 15도면 +15

#해상도 640*480 일때 내적 파라미터
camera:
  fx: 505.0742
  fy: 531.2114
  cx: 352.6202
  cy: 135.9729
  height: 0.75
  pitch_deg: -14.5



marker:
  enable: true
  ns: car_projected
  id: 0
  type: sphere
  scale: 0.2
  lifetime: 0.2
  color_rgba: [0.0, 0.2, 1.0, 1.0]
  z: 0.0
