image_topic: /cam2/usb_cam/image_raw
state_topic: /traffic_light/state
weights: /home/vic/kkdws/src/object_detector/model/best_traffic_med_yolo.pt
conf_th: 0.25
iou_th: 0.45
traffic_light_class_id: -1
min_box_area: 144
