vehicle:
  full_left_steer: 18
  full_right_steer: -22.5
  forward_speed: 175
  backward_speed: -100

timing:
  pause: 0.5
  parking_pause: 2.5
  going_right: 4
  detection_start: 2
  pull_out: 1

threshold:
  can_park: -2.5
  ultrasonic: 1000
  track_max_dist: 1.0

roi:
  lane:
    x_min: -1.0
    x_max:  1.0
    y_min: -3.0
    y_max: -1.0

  full_left:
    r_min: 1.2
    r_max: 2.8
    angle_deg: 60
  
  lost:
    r_min: 1.2
    r_max: 2.8
    angle_deg: 180

stanley_path:
  back_len: 2.0
  front_len: 5.0
  step: 0.1
  frame_id: "laser"