planner_common:
  roi:
    min_x: 0.0
    max_x: 1.0
    min_y: -0.3
    max_y: 0.3 #왼쪽
    offset_x: 0.7
  ultrasonic:
    threshold: 500.0
    unit_scale: 0.001   # mm -> m
    # (막대 굵기/알파 같은 건 rviz 전용으로 빼도 됨)

final_planner:
  rate_hz: 20
  default_motor: 0
  speed_0: 0
  speed_mid: 150
  speed_high: 255
  lc_steer: 22.5
  steer_time: 1
  straight_time: 1
  queues_maxlen: 10
  yolo_count_threshold: 7
  ultrasonic_count_threshold: 7
  traffic_red_threshold: 5
